#!/bin/bash
# Copyright (c) 2025  Logic Magicians Software.
# All Rights Reserved.
# Licensed under Gnu GPL V3.
#
# This wrapper script facilitates invoking the self-review Python
# script.
#
set -o errexit;
set -o nounset;
set -o pipefail;

SCRIPT="${BASH_SOURCE[0]}"
SCRIPT_DIR=$(dirname "${SCRIPT}");


function readlinkf ()
{
    local pn="${1}";

    if [[ "${pn}" != /* ]]; then
        pn="$(pwd)/${pn}";
    fi

    while [ -L "${pn}" ]; do
        pn=$(ls -l "${pn}" | sed 's/.*-> //');

        if [[ "${pn}" != /* ]]; then
            pn="$(dirname "$1")/${pn}";
        fi;
    done;

    echo "$(cd "$(dirname "${pn}")" && pwd)/$(basename "${pn}")";
}


function fatal ()
{
    local msg="${1}";
    
    echo "fatal: ${msg}";
    exit 10;
}


function main()
{
    readlinkf ${SCRIPT_DIR}/scripts.d/claude-qt.d

    local python=$(which python3);
    local options="-b -B";
    local claudeqt="$(readlinkf ${SCRIPT_DIR}/scripts.d/claude-qt.d)";
    local vrt="$(readlinkf ${SCRIPT_DIR}/scripts.d/vrt.d/vrt.py)";

    if [ -z "${python}" ] ; then
        cat <<EOF

No Python 3 interpreter was found on the path.
Put a Python 3 interpreter on the path to execute this tool.

EOF
        fatal "No Python 3 interpreter on \${PATH}.";
    fi;

    if [ -r "${vrt}" ] ; then
        if [ -z "${PYTHONPATH:-}" ] ; then
            export PYTHONPATH="${claudeqt}";
        else
            export PYTHONPATH="${PYTHONPATH}:${claudeqt}";
        fi;
        exec ${python} ${options} "${vrt}" "$@";
    else
        fatal "Unable to read '${vrt}'";
    fi;
}

main $@;
